### ISSUE TITLE
OTP 21.3 on Windows seen as 21

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [gleam-lang/setup-erlang#10]
It seems that https://github.com/gleam-lang/setup-erlang/blob/main/main.ps1#L4 might actually force 21.3 to become 21, in Windows, thus not allowing for CI over 21.3.

@lpil, is there a workaround for this? Is this behaviour on purpose for some unknown reason?

**Comment by lpil** [comment]
I think this is a limitation of the existing system and an upgrade to improve this would be welcome

**Comment by paulo-ferraz-oliveira** [comment]
I've worked around this using `erlef/setup-beam` (and implementing Windows support for it).
