### ISSUE TITLE
not working with Erlang/OTP versions that end with 0

### ISSUE THREAD

**Issue by moritzploss-k** [gleam-lang/setup-erlang#12]
Hey!

Thanks for making this super nice GitHub Action!

Maybe I'm doing something wrong, but I get a `Not Found` error at the `Downloading Erlang/OTP` step for Erlang/OTP versions that end with `0`, like 23.0 and 24.0. Here's the step that fails:

```
 Downloading Erlang/OTP 23 package
--2021-07-14 14:53:05--  https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_24-1~ubuntu~focal_amd64.deb

```

It fails because the Erlang/OTP version in the link is missing a trailing `.0`; the correct link would be:

```
https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_24.0-1~ubuntu~focal_amd64.deb
```

It works fine for Erlang/OTP 23.2 and 24.0.2.

**Comment by moritzploss-k** [comment]
I found that it works if I add quotation marks. So `'24.0'` and `"24.0"` works, but `24.0` doesn't. Probably a limitation of how inputs are parsed on GitHub's side. It's good enough for my purposes, but maybe the examples in the README should have quotation marks as well then? I'd be happy to make a PR for that!

**Comment by lpil** [comment]
Ah yes, this is YAML being a pain. A pull request adding quotes sounds like a good idea, thank you
