### ISSUE TITLE
Unable to run escript on Windows

### ISSUE THREAD

**Issue by Rory-Z** [gleam-lang/setup-erlang#6]
Hi, I tried to execute this action on `windows-latest`, it seems to be successful, but when I build my own application, I get an error: `env: 'escript': No such file or directory`. Am I missing something?

This is my actions: https://github.com/emqx/emqx-rel/pull/621/checks?check_run_id=1511081491

**Comment by lpil** [comment]
I'm not entirely sure if the Windows installer includes the escript program. It may be worth starting the investigation there.

https://github.com/gleam-lang/setup-erlang/blob/57dd49fa2fd2406f836a227c87977466e7270fa4/main.ps1#L23

**Comment by Rory-Z** [comment]
Hi, @lpil thank you for your reply
I noticed that Erlang was installed to `C:\Program Files\erl10.4`, which does not seem to be in the `$PATH` of windows. Could this be the cause of escript not being found?

**Comment by lpil** [comment]
Good to hear that it is included! I am quite new to windows so I'm not sure why that directory isn't on the path. I would have assumed the ESL installer would have done that.

**Comment by Rory-Z** [comment]
Hi, @lpil 

I tried to add `C:\Program Files\erl10.4\bi` to `$PATH`, like this: https://github.com/emqx/emqx-rel/runs/1518210211?check_suite_focus=true#step:5:4

But it still failed. Do you have any ideas?

**Comment by lpil** [comment]
I do not. I'm afraid I am very new to windows.￼

**Comment by Rory-Z** [comment]
@lpil 
I tried to repeat the windows example in the `README`, it worked, thx
