### ISSUE TITLE
No Windows build (on OTP 24)

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [gleam-lang/setup-erlang#8]
It [seems there's no build from Erlang Solutions](https://github.com/erlware/relx/pull/870#issuecomment-845136496) for Erlang/OTP 24.0 over Windows.

There's [plans for `setup-beam`](https://github.com/erlef/setup-beam) to eventually support this, but it still doesn't. 😢 

Would it be possible to include this in the PowerShell script? We can get the release from 
`http://erlang.org/download/otp_win64_<ver>.exe` (`<ver>` is `22.0`, `23.1`, `24.0`, etc.), for example, or GitHub (`https://github.com/erlang/otp/releases/download/OTP-<ver>/otp_win64_<ver>.exe`)

I'd suggest doing it from 24.0 onward, for the time being.

I'd pull request, but don't have a readily accessible Windows machine to use, at the moment.

Thanks.

**Comment by lpil** [comment]
Oh that is tricky. I think your suggestion is the way to go. We can verify the behaviour using a test for the new higher versions https://github.com/gleam-lang/setup-erlang/blob/main/.github/workflows/test.yml#L25

**Comment by paulo-ferraz-oliveira** [comment]
Thanks, @lpil. I agree that testing it is important 😄.

**Comment by paulo-ferraz-oliveira** [comment]
@lpil, do you think you'd be able to work on this soon? Or do you prefer me to try and tackle it?

**Comment by lpil** [comment]
Hello! I'm afraid I'm rather busy at the moment so I'm unlikely to have time to tackle this one. If you or someone else would like to pick this up please go ahead. Thanks

**Comment by paulo-ferraz-oliveira** [comment]
Oh, sure. It'll be good learning experience to later integrate in `setup-beam`.
If it becomes too hard, then I do it there only, and we can later add support for Gleam :)

**Comment by lpil** [comment]
Oh that would be really cool!

**Comment by paulo-ferraz-oliveira** [comment]
> If it becomes too hard, then I do it there only, and we can later add support for Gleam :)

Hi, @lpil. I've added Erlang 21+ support for Windows builds on `setup-beam` already, so this request might not be valid anymore. I'm Ok with you closing it, if you feel there's no need to track anything here.

**Comment by lpil** [comment]
Thank you @paulo-ferraz-oliveira .

Does `setup-beam` do everything this action does? If so I'm happy to deprecate this one and direct people to `setup-beam`.

**Comment by paulo-ferraz-oliveira** [comment]
> Thank you @paulo-ferraz-oliveira .
> 
> Does `setup-beam` do everything this action does? If so I'm happy to deprecate this one and direct people to `setup-beam`.

Hey. I'm not sure, since I didn't dig deep enough. `setup-beam` installs Erlang + rebar3 + Elixir + mix and works over version ranges (e.g. 12.3 might become 12.3.6). It does this on top of Windows and Ubuntu. If `setup-erlang` does more, let me know and I'll try to find time to port it to `setup-beam`. Thanks for your consideration.

**Comment by paulo-ferraz-oliveira** [comment]
Hm... at a glance it seems `setup-erlang` might even have been an inspiration for `setup-erlang`. Look at this I recently removed: https://github.com/erlef/setup-beam/pull/45/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L128 and compare it to your README 😄

**Comment by paulo-ferraz-oliveira** [comment]
Also, at a glance, it seems `setup-beam` covers `setup-erlang` completely. If I find some of the users/repo.s of this action I can probably test if moving to `setup-beam` is feasible.
